---
meta:
  title: Prosebook
  description: Prosebook
  url: https://craigerskine.github.io/prosebook/
  author: Craig Erskine
  author_url: https://craigerskine.com

social:
  - title: GitHub
    url: https://github.com/craigerskine/prosebook/
    ico: simple-icons:github
    color: neutral

footer:
  - title: Sitemap
